# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-netlify-toml-file
# https://docs.netlify.com/routing/headers/#custom-headers 
# https://gist.github.com/robsonsobral/5b8d1ff10a10dd35793a768f8531cc18

[[redirects]]
  from = "/atom.xml"
  to = "https://cfblog.17lai.site/atom.xml"
  
[[redirects]]
  from = "/rss.xml"
  to = "https://cfblog.17lai.site/rss.xml"
  
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/medias_webp/**"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/libs/**"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/data/**"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/media/**"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, s-max-age=1800"
[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.lrc"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "*.mp3"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, s-max-age=43200"
[[headers]]
  for = "*.xml"
  [headers.values]
    Cache-Control = "public, s-max-age=43200"
    
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
