# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-netlify-toml-file

[[redirects]]
  from = "/atom.xml"
  to = "https://cfblog.17lai.site/atom.xml"
  
[[redirects]]
  from = "/rss.xml"
  to = "https://cfblog.17lai.site/rss.xml"
  
[[headers]]
  for = "(.*).webp"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).png"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).jpg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).svg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).ttf"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).woff"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).woff2"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/medias_webp/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).html"
  [headers.values]
    Cache-Control = "public, s-max-age=1800"
[[headers]]
  for = "(.*).css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).lrc"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "(.*).mp3"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    
